# Generated by Django 5.1.2 on 2024-11-19 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login'),
        ),
    ]
