# Generated by Django 5.1.2 on 2024-11-29 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_foto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='usuarios/'),
            preserve_default=False,
        ),
    ]
