# Generated by Django 5.1.2 on 2024-11-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='usuario',
        ),
    ]
