# Generated by Django 5.1.2 on 2024-12-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_foto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='media/usuarios/'),
        ),
    ]
