# Generated by Django 5.1.3 on 2024-12-03 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_fotos_foto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='curso/'),
            preserve_default=False,
        ),
    ]
