# Generated by Django 5.1.4 on 2024-12-05 21:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_curso_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='app.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='app.usuario')),
            ],
        ),
    ]
